###### DEV PIPELINE ######
image: docker:28.2.2

services:
  - name: docker:28.2.2-dind
    alias: docker
    command: ["--tls=false", "--mtu=1240"]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  REGISTRY_URL: "registry.nosi.cv"
  REGISTRY_PROJECT: "aed80fae-ad01-4bec-ba1c-31f1179887b6"
  IMAGE_NAME: "sgc-cemiteries-frontend"

stages:
  - build
  - deploy

build_docker_image:
  stage: build
  only:
    - main
  script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" $REGISTRY_URL
    - docker build -t $REGISTRY_URL/$REGISTRY_PROJECT/$IMAGE_NAME:$CI_PIPELINE_ID .
    - docker tag $REGISTRY_URL/$REGISTRY_PROJECT/$IMAGE_NAME:$CI_PIPELINE_ID $REGISTRY_URL/$REGISTRY_PROJECT/$IMAGE_NAME
    - docker push $REGISTRY_URL/$REGISTRY_PROJECT/$IMAGE_NAME:$CI_PIPELINE_ID
    - docker push $REGISTRY_URL/$REGISTRY_PROJECT/$IMAGE_NAME

deploy:
  image: gcc:latest
  stage: deploy
  only:
    - main
  script:
    - |
      curl -u "$DEPLOY_USER:$DEPLOY_PASSWORD" \
        -X POST \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        'https://manager.nosi.cv/v3/project/c-kthdc:p-tn7qs/workloads/deployment:aed80fae-ad01-4bec-ba1c-31f1179887b6:sgc-cemiteries-frontend?action=redeploy'